version: 1
update_configs:
  # Keep requirements.txt files up-to-date in each package.
  - package_manager: "python"
    directory: "/dvp"
    update_schedule: "monthly"
    target_branch: "develop"
  - package_manager: "python"
    directory: "/common"
    update_schedule: "monthly"
    target_branch: "develop"
  - package_manager: "python"
    directory: "/platform"
    update_schedule: "monthly"
    target_branch: "develop"
  - package_manager: "python"
    directory: "/libs"
    update_schedule: "monthly"
    target_branch: "develop"
  - package_manager: "python"
    directory: "/tools"
    update_schedule: "monthly"
    target_branch: "develop"
